### ISSUE TITLE
Allow to input a data frame instead of an iterator for ScorerCache

### ISSUE THREAD

**Issue by janheinrichmerker** [seanmacavaney/pyterrier-caching#6]
For huge corpora like the ClueWebs, I'd like to avoid iterating over the full corpus.
Rather, I'd just pass the output of some retriever applied to some topics to the scorer cache's build function.
Is this setting supported?

**Comment by seanmacavaney** [comment]
Thanks for reporting @janheinrichmerker!

I agree that this is burdensome. Right now you can alternatively pass a [npids](https://pypi.org/project/npids/) docid file [into build](https://github.com/seanmacavaney/pyterrier-caching/blob/main/pyterrier_caching/scorer_cache.py#L34) to avoid iterating over the full collection. But to build the file, you'd have to have all docnos to begin with. (Perhaps there's a list of all ids somewhere?)

But even with this, I don't think the current ScorerCache implementation would work all that well for the ClueWebs, since it allocates a dense vector to store the scores for each document in the corpus. This will get huge. This design was based on my original use case, which involved scoring every document in msmarco with a cross encoder. But in hindsight, that's not a typical use case.

I'm thinking about an alternative implementation that stores as sparse vectors and avoids the build step entirely. Perhaps something that makes a [dbm file](https://docs.python.org/3/library/dbm.html) for each query, with the file name as the query hash and the key as the docid. Or a sqlite database? What are your thoughts on this?

cc @Parry-Parry

**Comment by janheinrichmerker** [comment]
Nice hearing your original thoughts on it :+1: 
I agree that the current implementation is perfect for your given use case. My use case would be more like this:
> I want to benchmark combinations of a bunch of retrievers (cached via `RetrieverCache`) and re-rankers similar to running a grid search. (One could also think of actually finding the optimal configuration in a grid search.)
With different retrievers, still very often the same documents are retrieved, or at least there is some common subset.
So when re-ranking the results of the second retriever, the re-ranking would just need to score the new documents that were not retrieved by the first retriever.
From what I can see, the `dbm` idea looks perfect for that. I haven't used Python's `dbm` yet, but it seems nice that it automatically switches the backend as needed, although that could also cause issues if the cache is used on a different device later on. Maybe then the sqlite option is the most portable way to implement it, plus it should be faster than dbm's "dumb" implementation.

**Comment by janheinrichmerker** [comment]
Maybe just explicitly using [`dbm.sqlite3`](https://docs.python.org/3/library/dbm.html#module-dbm.sqlite3) would solve it?

**Comment by seanmacavaney** [comment]
> My use case would be more like this:

Great- I think this use case is probably way more common than the one I had.

> Maybe just explicitly using [dbm.sqlite3](https://docs.python.org/3/library/dbm.html#module-dbm.sqlite3) would solve it?

I'll give it a try when I have the chance!

**Comment by seanmacavaney** [comment]
I've put together an implementation that uses [dbm.sqlite3](https://docs.python.org/3/library/dbm.html#module-dbm.sqlite3) and avoids the need for a first pass in #7. Can you take a look when you have the chance?

**Comment by janheinrichmerker** [comment]
Very nice indeed!
I only now noticed that the `dbm.sqlite3` module is only available from Python 3.13 onwards.
Then, it might even be easier to just use pure SQLite right away or use some abstraction ontop of SQLite that you don't need to maintain for yourself.
I have used [`diskcache`](https://grantjenks.com/docs/diskcache/) in the past (e.g., for the caching in ir_axioms).
It is very stable and fast, and would even allow for some other shenanigans like cache expiration and eviction with LRU. Do you think it could be worthwhile looking at that library?

**Comment by seanmacavaney** [comment]
`diskcache` looks promising and has some useful features, but I like relying on the standard library when possible to avoid external dependencies.

I'm not worried about maintenance of the `dbm.sqlite3` polyfill since I was able to just use cpython's implementation: https://github.com/python/cpython/blob/3.13/Lib/dbm/sqlite3.py (with a few minor modifications to adhere to older python syntax, like replacing the `match` block with `if` statements).

**Comment by seanmacavaney** [comment]
Alright, after a bit of benchmarking, it turns out that using DBM's implementation wasn't particularly efficient. Especially for inserts, but for reads, too. This was in part because it operates a single record at a time, rather than being able to do batch operations.

I wrote a new version that uses sqlite3 directly. I've also taken the opportunity to make it a bit more flexible (configurable query/docno/score columns), and added merging functionality requested by @Parry-Parry. The implementation also performs a single scoring step, rather than multiple ones (as requested in #5).

An additional advantage over the previous dense HDF5 implementation is that it should have better concurrency support. (Though I have not tested this directly.)

PR #7 should be good to go. Would you mind having a peek at it to check that it meets your needs, @janheinrichmerker?

**Comment by janheinrichmerker** [comment]
Very nice Sean! As always, fantastic work :+1:
